version: "3"

services:
  yt-dlp-web:
    image: sooros5132/yt-dlp-web
    container_name: yt-dlp-web
    user: 1000:1000
    environment:
      - PODCAST_PORT=3001
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   AUTH_SECRET: "Random_string,_40+_characters_recommended"
    #   CREDENTIAL_USERNAME: "username"
    #   CREDENTIAL_PASSWORD: "password"
    volumes:
      - ~/Desktop/downloads:/downloads
      - ~/Desktop/cache:/cache
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
